[package]
name = "snake"
version = "0.1.0"
edition = "2024"
description = "a small wasm snake game"
license = "GPL-3.0"
repository = "https://github.com/plexx-dev/plexx.dev/tree/master/game_files/snake"

[lib]
crate-type = ["cdylib", "rlib"] # Compile as a shared library for WASM

[dependencies]
rand = { version = "0.10.0"}
wasm-bindgen = "0.2"
getrandom = { version = "0.4.1", features = ["wasm_js"] }

[dev-dependencies]
wasm-bindgen-test = "0.3.58"

[profile.release]
opt-level = "s"
