[package]
name = "plexx-dev"
version = "0.1.0"
edition = "2024"
description = "a small website"
license = "GPL-3.0"
license-file = "LICENSE"
repository = "https://github.com/plexx-dev/plexx.dev"

[dependencies]
rocket = "0.5.1"
rocket_dyn_templates = { version = "0.2.0", features = ["tera"] }

[workspace]
members = [
    ".",
    "game_files/snake",
    "game_files/conway",
]